services:
  app:
    build: .
    env_file: .env
    environment:
      - ENV_POSTGRES_HOST=db
      - ENV_POSTGRES_URL=postgresql://${ENV_POSTGRES_USER}:${ENV_POSTGRES_PASSWORD}@db:${ENV_POSTGRES_PORT}/${ENV_POSTGRES_DB}
    ports:
      - "8000:8000"
    command: sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000"
    depends_on:
      - db

        

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env
    environment:
      POSTGRES_DB: ${ENV_POSTGRES_DB}
      POSTGRES_USER: ${ENV_POSTGRES_USER}
      POSTGRES_PASSWORD: ${ENV_POSTGRES_PASSWORD}
    ports:
      - "${ENV_POSTGRES_PORT}:${ENV_POSTGRES_PORT}"

volumes:
  postgres_data:
